name: Docs to PDF and Upload Release Asset

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows'
      - 'README.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: .
          output_dir: .
          images_dir: .
          # for example <img src="./file-name.png">
          image_import: .
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v3
        with:
          name: David_Wasilewski_Resume.pdf
          path: .
  build:
    name: Upload Release Asset
    needs: converttopdf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          mkdir -p app/build/outputs/apk/release
          echo hello > app/build/outputs/apk/release/app-release-unsigned.apk
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/apk/release/app-release-unsigned.apk
            other/files/as/needed
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN }}
