name: MD to PDF Conversion

on:
  push:
    branches:
      - main

jobs:
  Convert:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate PDF from Markdown Files
        uses: purplebearddan/ghAction-md2pdf@v1
        with:
          pdf_file_name: 'David_Wasilewski_Resume.pdf'
