on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - '.github/workflows/convert-to-pdf.yml'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install pandoc
      - name: Convert Markdown to PDF
        run: pandoc --pdf-engine=weasyprint /github/workspace/README.md -o README.pdf
      - uses: actions/upload-artifact@v3
        with:
          name: David_Wasilewski_Resume
          path: .
