name: Convert README to PDF

on:
  push:
    branches:
      - main  # Adjust this branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install -g md-to-pdf

      - name: Create output folder
        run: mkdir -p _output

      - name: Convert README to PDF
        run: |
          cd path/to/your/markdown/files  # Adjust the path to your markdown files
          for f in *.md; do
            cat "$f"
            echo
          done | md-to-pdf > ../_output/result.pdf
