name: Convert and Rename Resume

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  convert-and-rename:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm init -y
          npm install marked
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Create conversion script
        run: |
          echo 'const fs = require("fs");
          const marked = require("marked");
          const { execSync } = require("child_process");
          
          const css = `
            <style>
              body {
                font-family: Arial, sans-serif;
                line-height: 1.6;
                max-width: 800px;
                margin: 20px auto;
                padding: 10px;
              }
              h1, h2, h3 {
                color: #2c3e50;
                margin-top: 1em;
              }
              h1 {
                margin-top: 0.5em;
              }
              a {
                color: #3498db;
                text-decoration: none;
              }
              a:hover {
                text-decoration: underline;
              }
              ul, ol {
                padding-left: 2em;
              }
              li {
                margin: 0.5em 0;
              }
              code {
                background: #f8f9fa;
                padding: 0.2em 0.4em;
                border-radius: 3px;
                font-family: monospace;
              }
              pre {
                background: #f8f9fa;
                padding: 1em;
                border-radius: 5px;
                overflow-x: auto;
              }
              blockquote {
                border-left: 4px solid #3498db;
                margin: 1em 0;
                padding-left: 1em;
                color: #666;
              }
              table {
                border-collapse: collapse;
                width: 100%;
                margin: 1em 0;
              }
              th, td {
                border: 1px solid #ddd;
                padding: 8px;
                text-align: left;
              }
              th {
                background-color: #f8f9fa;
              }
            </style>
          `;
          
          const md = fs.readFileSync("README.md", "utf8");
          const html = marked.parse(md);
          const fullHtml = `<!DOCTYPE html>
            <html>
              <head>
                <meta charset="utf-8">
                ${css}
              </head>
              <body>
                ${html}
              </body>
            </html>`;
          
          fs.writeFileSync("temp.html", fullHtml);
          execSync("wkhtmltopdf --enable-local-file-access --margin-top 10 --margin-right 20 --margin-bottom 20 --margin-left 20 --enable-external-links --enable-internal-links --javascript-delay 1000 temp.html David_Wasilewski_Resume.pdf");
          fs.unlinkSync("temp.html");' > convert.js

      - name: Convert MD to PDF
        run: node convert.js

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -f David_Wasilewski_Resume.pdf
          git commit -m "Update resume PDF"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
