name: Convert and Rename Resume

on:
  push:
    branches:
      - main

jobs:
  convert-and-rename:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Pandoc
        uses: docker://pandoc/core:3.1
        with:
          args: >-
            README.md
            -o David_Wasilewski_Resume.pdf
            --pdf-engine=wkhtmltopdf
            --standalone

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add David_Wasilewski_Resume.pdf
          git commit -m "Update resume PDF"
          git push
