name: Convert and Rename Resume

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  convert-and-rename:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm init -y
          npm install marked puppeteer

      - name: Create conversion script
        run: |
          echo 'const fs = require("fs");
          const marked = require("marked");
          const puppeteer = require("puppeteer");
          
          const css = `
            <style>
              body {
                font-family: Arial, sans-serif;
                line-height: 1.4;
                max-width: 800px;
                margin: 10px auto;
                padding: 5px;
                font-size: 10pt;
              }
              h1 {
                color: #2c3e50;
                margin-top: 0.5em;
                font-size: 30pt;
              }
              h2, h3 {
                color: #2c3e50;
                margin-top: 0.5em;
                font-size: 12.5pt;
              }
              a {
                color: #3498db;
                text-decoration: none;
              }
              a:hover {
                text-decoration: underline;
              }
              ul, ol {
                padding-left: 1.5em;
              }
              li {
                margin: 0.25em 0;
              }
              p {
                margin: 0.25em 0;
              }
              code {
                background: #f8f9fa;
                padding: 0.1em 0.2em;
                border-radius: 3px;
                font-family: monospace;
                font-size: 8.75pt;
              }
              pre {
                background: #f8f9fa;
                padding: 0.5em;
                border-radius: 5px;
                overflow-x: auto;
                font-size: 8.75pt;
              }
              blockquote {
                border-left: 4px solid #3498db;
                margin: 0.5em 0;
                padding-left: 0.5em;
                color: #666;
              }
              table {
                border-collapse: collapse;
                width: 100%;
                margin: 0.5em 0;
              }
              th, td {
                border: 1px solid #ddd;
                padding: 4px;
                text-align: left;
              }
              th {
                background-color: #f8f9fa;
              }
            </style>
          `;
          
          async function convert() {
            const md = fs.readFileSync("README.md", "utf8");
            const html = marked.parse(md);
            const fullHtml = `<!DOCTYPE html>
              <html>
                <head>
                  <meta charset="utf-8">
                  ${css}
                </head>
                <body>
                  ${html}
                </body>
              </html>`;
            
            fs.writeFileSync("temp.html", fullHtml);
            
            const browser = await puppeteer.launch({
              headless: "new",
              args: ["--no-sandbox", "--disable-setuid-sandbox"]
            });
            const page = await browser.newPage();
            
            await page.setJavaScriptEnabled(true);
            
            await page.setViewport({
              width: 1200,
              height: 800,
              deviceScaleFactor: 2
            });
            
            await page.goto(`file://${process.cwd()}/temp.html`, {
              waitUntil: "networkidle0"
            });
            
            await page.evaluate(() => {
              return new Promise((resolve) => {
                setTimeout(resolve, 1000);
              });
            });
            
            await page.pdf({
              path: "David_Wasilewski_Resume.pdf",
              format: "A4",
              margin: {
                top: "10mm",
                right: "20mm",
                bottom: "20mm",
                left: "20mm"
              },
              printBackground: true,
              preferCSSPageSize: true,
              displayHeaderFooter: false
            });
            
            await browser.close();
            fs.unlinkSync("temp.html");
          }
          
          convert();' > convert.js

      - name: Convert MD to PDF
        run: node convert.js

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -f David_Wasilewski_Resume.pdf
          git commit -m "Update resume PDF"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
